fix: delete aws
ca-risken/aws pull request #228
Opened 2022-05-13 10:18 UTC by gassara-kys

DeleteAWSで関連データを削除する処理を追加（データ不整合が起きてしまうため）

ref https://github.com/ca-risken/internal-community/issues/269

2022-05-13 10:42 UTC, mmmknt approved these changes
👍

2022-05-13 11:20 UTC, mmmknt requested changes
すいません、確認したらコメントありました:pray:

2022-05-13 11:20 UTC, mmmknt commented on src/aws/service.go
> +	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
単一オブジェクトの取得でないなら対象のデータが存在しない場合でも `ErrRecordNotFound`は返ってこないので後半の条件は不要だと思います
https://gorm.io/ja_JP/docs/error_handling.html

2022-05-13 11:20 UTC, mmmknt commented on src/aws/service.go
> +	list, err := a.repository.ListDataSource(ctx, req.ProjectId, req.AwsId, "")
`aws_data_source`テーブルに存在しないデータが`aws_rel_data_source`に登録されていた場合に削除が漏れるので、`aws_rel_data_source`から削除対象のデータを取得した方が良いです

2022-05-13 12:49 UTC, gassara-kys commented on src/aws/service.go
> +	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
修正しました！

2022-05-13 12:49 UTC, gassara-kys commented on src/aws/service.go
> +	list, err := a.repository.ListDataSource(ctx, req.ProjectId, req.AwsId, "")
修正しました！対象エンティティのリスト取得のメソッドがなかったので新規追加しています。

2022-05-17 03:59 UTC, mmmknt approved these changes
👍

2022-05-18 00:41 UTC, merged